### ISSUE TITLE
Shopping cart is not being cleared after successful purchase

### ISSUE THREAD

**Issue by stevenobird** [heidelpay/magento2#12]
When doing a checkout with one of the heidelpay payment methods, the cart's content will remain the same after successful checkout.

**Comment by DavidLambauer** [comment]
Can you provide more details about your environment? For example, Magento Version, PHP Version, Heidelpay Version.

Are there any entries in your log files (Application log and PHP Log)?

**Comment by heidelpay** [comment]
The mini cart on the success page  apears to have items in cart but doesn't. Seems to be an issues on all magento 2 version. But could be a luma template thing? Can somebody check if it´s also on other templates?

**Comment by heidelpay** [comment]
He have find a solution. This will be fixed in the next release.

regards
Jens

**Comment by heidelpay** [comment]
Fixed with PR #17
