### ISSUE TITLE
Add support for Magento 2.4.0

### ISSUE THREAD

**Issue by Emanuel-23** [heidelpay/magento2#144]
Please add support for Magento 2.4.0.

**Comment by cmuench** [comment]
We need also support for Magento 2.4 for some customers.
Any release plans?

**Comment by Ryouzanpaku** [comment]
Hey there, we are planning an update. It will be released after we tested it successfully with Magento 2.4.

**Comment by cmuench** [comment]
@Ryouzanpaku Thanks for the response. Maybe you can update the issue here if there is any update which can be testet.

**Comment by Ryouzanpaku** [comment]
New module version for Magento 2.4 is now available.
