### ISSUE TITLE
Magento 2.4 / Integration Tests setUp method is invalid

### ISSUE THREAD

**Issue by cmuench** [heidelpay/magento2#148]
My local test suite crashes due to invalid Integration tests classes.

```
PHP Fatal error:  Declaration of Heidelpay\Gateway\Test\Integration\IntegrationTestAbstract::setUp() must be compatible with Magento\TestFramework\TestCase\AbstractController::setUp(): void in /var/www/html/vendor/heidelpay/magento2/Test/Integration/IntegrationTestAbstract.php on line 96

Fatal error: Declaration of Heidelpay\Gateway\Test\Integration\IntegrationTestAbstract::setUp() must be compatible with Magento\TestFramework\TestCase\AbstractController::setUp(): void in /var/www/html/vendor/heidelpay/magento2/Test/Integration/IntegrationTestAbstract.php on line 96
```

The declaration is not compatible with PHPUnit 9 (used by Magento 2.4)

The curious thing is that I did not try to run any of the Heidelpay Integration Tests. PHPUnit seems to lod them within Composer autoloading process which let PHP crash.

I manually patched all `setUp` methods. After that all my tests startet again.

**Comment by Ryouzanpaku** [comment]
@cmuench,
thanks for the info. We will check that for next update.

**Comment by sixer1182** [comment]
Hi @cmuench 
Sadly there will be no more updates in this project.

Best regards,
Simon
