### ISSUE TITLE
Pay with Invoice Error:  Heidelpay - Redirect: Redirect with error to cart: Birthdate missing [] []

### ISSUE THREAD

**Issue by roman204** [heidelpay/magento2#149]
module version: 20.5.13
magento 2.3.3

When someone tries to checkout with invoice and has no birthday set, a entry in system.log of magento gets logged and the user gets redirected to cart.
"Heidelpay - Redirect: Redirect with error to cart: Birthdate missing [] []" is logged and the customer gets redirected.
The birthdate field is not mandatory in our shop. But i didn't found a requirement for it in your documents.

**Comment by Ryouzanpaku** [comment]
Hello @roman204,
please contact our support via e-mail for that issue. Our new e-mail-address for that is support@unzer.com
