### ISSUE TITLE
Difference to Magento 2 Merchant Gateway

### ISSUE THREAD

**Issue by HenKun** [heidelpay/magento2#150]
What is the difference between this module and https://github.com/heidelpay/magento2-merchant-gateway ? 
Both seem to offer different payment methods via heidelpay and both seem to be maintained more or less.

**Comment by unzer-sp** [comment]
Hello @HenKun , 
The difference is, that https://github.com/heidelpay/magento2 uses another payment-gateway of unzer (former heidelpay). Maintenance and support for https://github.com/heidelpay/magento2 will end soon and Unzer only provides bugfixes for that extension and no more features like compatibility to higher magento versions. 
To use the https://github.com/heidelpay/magento2-merchant-gateway extension you need new login-data, called "keypairs". For further informations please contact support@unzer.com 

kind regards and best wishes
Sascha Pflüger
Merchant Connectivity Support

**Comment by HenKun** [comment]
Thanks @unzer-sp It might be helpful for others if this is stated somewhere in the Github Repos or in a blog post, since this closed issue is again not visible to others. We started integrating this module, which we found on Google, which is deprecated and have to switch to the merchant gateway now.
Nevertheless, best wishes and a merry Christmas!
