### ISSUE TITLE
Publish version guidelines

### ISSUE THREAD

**Issue by andrewhowdencom** [heidelpay/magento2#28]
In adding this to composer, I was just looking at how to denote the version. How do you decide what's a major, minor or patch version? It'd be good to see docs on this

**Comment by heidelpay** [comment]
Hello,

right now, we don't make any differences between major and minor updates.
The version just refers to it's release date - so our latest version 17.7.25 was released on July, 25th in 2017.

Regards,
Stephano

**Comment by andrewhowdencom** [comment]
Would be resolved by https://github.com/heidelpay/magento2/compare/master...andrewhowdencom:patch-1

Thanks Stephano!

**Comment by andrewhowdencom** [comment]
Opened #29

**Comment by heidelpay** [comment]
Hi andrew,

I've merged your PR to make our versioning (for now) clear.
