### ISSUE TITLE
[Bug] Secured Invoice is sometimes not being shown as selectable method in guest checkout

### ISSUE THREAD

**Issue by devheidelpay** [heidelpay/magento2#35]

**Comment by nsiebler-dm** [comment]
We spotted a problem that is very similar and maybe related.
It's also the case when a logged in user will select a shipping method in the checkout, the proceeds  to the payment selection/review and then decides to go back to change the shipping address. 

The payment method afterwards will just show up or not show at all like the initially selected address was still selected. A full page reload with new shipping selection fixes this issue, but it should also work with AJAX changes when going back to the shipping address page in the checkout and proceeding then.

**Comment by stevenobird** [comment]
Hello @nsiebler-dm !

we had reports regarding this issue in the past and could not find anything on our side that causes this behaviour. We are not touching anything before the selection of the payment methods during the checkout - so if the shipping/billing address is not set, it will be an issue on the Magento (our another 3rd party plugin) side.

Best regards,
Stephano
