### ISSUE TITLE
2.2 support

### ISSUE THREAD

**Issue by andrewhowdencom** [heidelpay/magento2#36]
Hola All, 

is the 2.2 support branch stable?

**Comment by andrewhowdencom** [comment]
It seems to require `magento/framework: ^100.*.*`, which is 2.1.9.x. I've seen this solved in other places with the constraint `^100.0 | ^101.0.0`; is this useful here also? Can do a PR

**Comment by stevenobird** [comment]
Hi,
`^100.*.*`  should include 2.0.0 to 2.1.9.

Regards,
Stephano

**Comment by andrewhowdencom** [comment]
oh this is running in 2.2 now so i guess it works. closing
