### ISSUE TITLE
Non-deterministic failure to complete payment method

### ISSUE THREAD

**Issue by andrewhowdencom** [heidelpay/magento2#41]
This one is a super hard bug! At the minute, all I can track it to "Heidelpay sometimes cannot be completed in the non-default store". All I can tell so far is the quote has disappeared - the phrase "An unexpected error occurred. Please contact us to get further information." is shown.

Looking into this. Haven't got any good solutions so far. 

~  Magento 2.2 

Not guaranteed to be Heidelpay related, but that's the consistently reproducible case so far.

**Comment by stevenobird** [comment]
Hello Andrew,

thanks for your report.

- Is that happening with every payment method?
- Do the quotes literally disappear (getting deleted) or can't they be found?
- Do the error logs show some helpful information? Check ```debug.log``` and ```system.log``` for "heidelpay" content.

Multi-Store should work, as we have also tested out (not in Magento 2.2, but we'll do that asap).
We are generating urls for API responses and Push messages with the ```'_scope_to_url'``` option set to true.

We are thankful for every bit of information! :)

Best regards,
Stephano

**Comment by andrewhowdencom** [comment]
Hola @stevenobird; 

As far as I can see, all Heidelpay methods, but not check / money order or bank transfer. Logs show nothing; it's just that Heidelpay is the only place I grepped that saw that phrase -- thus the bug report. The quotes disappear from the point of view o the client; I haven't checked in the DB. 

My suspicion is the session is being invalidated somehow, in which case it's an environment specific bug. However, I will update this bug with more information as I find it.

**Comment by stevenobird** [comment]
Are the orders being created or what is happening on customer side?

If yes - we had some customers where 3rd party plugins were deleting some session variables that redirected back to (an empty) cart instead of 'checkout/onepage/success' - the check that fails is the ```isValid()``` method in the ```Magento\Checkout\Model\Session``` class. We are setting those session vars in our code right before we are redirecting the customer.

If not - we need some more information.

Thanks in advance!
Stephano

**Comment by andrewhowdencom** [comment]
It's going wrong during the redirect I think (thus no orders are created). Dumping `debug_print_backtrace()` in there killed it, but it was processing the request for `/hgw` I think. I'll play with this more tomorrow -- this issue was a stub; no action is required on your part yet (: (though if someone has had the issues before feel free to jump in)

**Comment by stevenobird** [comment]
Hi Andrew,

can you show us some of your configurations regarding the multi-store setup?

Regards,
Stephano

**Comment by andrewhowdencom** [comment]
I'm not sure what you mean. "Configuration" is somewhat broad. Loosely, they're all on the same domain, and they use cookies to differentiate the store. It's behind varnish. 

Won't share specific details (like who it is) because privacy. (:

**Comment by andrewhowdencom** [comment]
One site had the wrong cookie domain set. Missed it as it was coupled with the 2.2 upgrade, and that it was not inheriting the default value. 

In related news, fuck.

Not heidelpay related. Showed up in heidelpay as you query the quote before the redirect; other stuff seems not to.

Non determinism appears to be related to one request which has different cookie handling. No idea what that's about.
