### ISSUE TITLE
After installing this modules all the enabled modules are mot showing in frontend checkout page

### ISSUE THREAD

**Issue by BabliDey** [heidelpay/magento2#42]
After installing this modules all the enabled modules like COD, CHECK ORDER, Bank TRANSFER are mot showing in frontend checkout page.

**Comment by stevenobird** [comment]
Hi,

that sounds new to us. We are not touching any other payment methods, so our module is able to co-exist with Magento's built-in modules like the ones you've listed.

Can you tell us more about your environment, like
* Magento Version
* heidelpay Gateway Version

Best Regards,
Stephano

**Comment by sixer1182** [comment]
@BabliDey since you didn't answer we assume this is not an issue anymore.
Please re-open if you still need our help.

Yours,
Simon
