### ISSUE TITLE
update composer requirements

### ISSUE THREAD

**Issue by Barbers** [heidelpay/magento2#47]
It look like the composer requirements and maybe also the code isn't updated to the latest heidelpay-api.
I get the following output from composer.

`Package heidelpay/php-customer-messages is abandoned, you should avoid using it. Use heidelpay/php-message-code-mapper instead.`

`Package heidelpay/php-api is abandoned, you should avoid using it. Use heidelpay/php-payment-api instead.`

And I also get:
`Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead.`
but this could be a magento requirement and not a heidelpay one.

**Comment by stevenobird** [comment]
Hi @Barbers !

Thanks for posting the issue.
Please be aware that those messages are warnings/recommentations, so please ignore that for now.

We're aware of that and already working on a bigger release that will use the updated dependencies.

Best regards,
Stephano
