### ISSUE TITLE
Feature-Request: make Short-ID available via SOAP Api

### ISSUE THREAD

**Issue by michaelscheel** [heidelpay/magento2#61]
Please make the Short-ID available via Magento SOAP Api. If you want to generate invoices for payment method „Secured Invoice" with a third-party-tool (e.g. ERP) it's currently not possible to get the Short-ID via SOAP as the table _heidelpay_transaction_ is not accessible.

There are at least two possible solutions:
1. Make table _heidelpay_transaction_ available via SOAP Api.
2. Add Short-ID to _sales_order_payment_, e.g. field additional_data or additional_information

Thank you!

**Comment by sixer1182** [comment]
Hi @michaelscheel,
the Short-ID identifies the transactions not the order.
Therefore there will be several Short-IDs per Order.

If you rely on this please talk to your sales contact to issue a feature request.
