### ISSUE TITLE
Missing required argument $paymentConfig of Heidelpay....

### ISSUE THREAD

**Issue by Torys87** [heidelpay/magento2#63]
Hello

After installing module, I got error:
Missing required argument $paymentConfig of Heidelpay\\Gateway\\PaymentMethods\\HeidelpayAbstractPaymentMethod.

when I try to go in admin/sales/orders and on frontend on checkout.

How is this problem can be solved?

in class constructor
heidelpay\magento2\PaymentMethods\HeidelpayAbstractPaymentMethod.php

I see:
$paymentConfig /* do not add Type or this wont work */,

when change it to \Magento\Payment\Gateway\Config\Config $paymentConfig

problem, maybe, was fixed, but I'm not sure. Also I'm not sure if it is correct way - it is bad practice to change something in vendor

**Comment by sixer1182** [comment]
Hi @Torys87
You are right. You should not change anything in vendor.
Did you perform the command 'bin/magento setup:di:compile' ?
It is necessary due to the changes within the file 'di.xml'.

Please keep me posted if this fixed the issue.

Best regards,
Simon

**Comment by sixer1182** [comment]
Hi @Torys87 ,
did the solution work?
Please give me your feedback.

Thanks,
Simon

**Comment by kemexyz** [comment]
This error does not show if you execute "bin/magento setup:di:compile" how ever it always returns when you install any other module in magento.

**Comment by sixer1182** [comment]
You should always perform
'bin/magento setup:upgrade' and 'bin/magento setup:di:compile'
when you install a module.

https://magefan.com/blog/how-to-install-magento-2-extension-2/

**Comment by nsiebler-dm** [comment]
@sixer1182 
We get this issue as well with Magento Commerce 2.2.4 and Heidelpay 18.4.23.
setup:di:compile should not be required for developer mode, but it fixes the mentiond problem for us. For development this is just a big time consumer.
Can you please check if this is really required for developer mode or just a problem on our side?

**Comment by sixer1182** [comment]
@nsiebler-dm 
I am sorry to hear that and will look into this issue.

**Comment by sixer1182** [comment]
We just released a bugfix in [Version 18.6.7](https://packagist.org/packages/heidelpay/magento2#18.6.7)
Please let me know whether this fixes the problems on your end.

Yours Simon.

**Comment by nsiebler-dm** [comment]
@sixer1182 
Many thanks, it's working in developer mode now without the compile command!

**Comment by sixer1182** [comment]
@nsiebler-dm thanks for your feedback.
I'll close the issue now.
