### ISSUE TITLE
Sandbox Mode of Basket API is always active

### ISSUE THREAD

**Issue by michaelscheel** [heidelpay/magento2#66]
setIsSandboxMode() in vendor/heidelpay/php-basket-api/lib/Request.php is called nowhere therefore sandbox mode is always active. The method generateUrl() always returns the url of the sandbox.

```php
    /**
     * Generates a url for the request.
     *
     * @param string|null $suffix The url suffix
     *
     * @return string
     */
    private function generateUrl($suffix = null)
    {
        $base = $this->isSandbox ? self::URL_TEST : self::URL_LIVE;

        return sprintf('%s%s', $base, $suffix);
    }
```

**Comment by sixer1182** [comment]
Hi @michaelscheel,
thanks for the info. I will fix this asap.

Yours Simon.

**Comment by sixer1182** [comment]
Hi @michaelscheel,
please update the plugin to the new version 8.6.11 which contains a fix for this issue.

Yours Simon.
