### ISSUE TITLE
Customer is redirected to cart after purchase when synchronous mail delivery is active and FPC is enabled

### ISSUE THREAD

**Issue by michaelscheel** [heidelpay/magento2#70]
When delivering order confirmation emails synchronously and having FPC enabled customers get redirected to cart after checkout session validation fails in vendor/magento/module-checkout/Model/Session/SuccessValidator.php because session is empty. Magento 2.2.3

```php
public function isValid()
    {
        if (!$this->checkoutSession->getLastSuccessQuoteId()) {
            return false;
        }

        if (!$this->checkoutSession->getLastQuoteId() || !$this->checkoutSession->getLastOrderId()) {
            return false;
        }
        return true;
    }
```

The session storage get's cleared by the plugin vendor/magento/module-checkout/Model/Layout/DepersonalizePlugin.php
```php
    public function afterGenerateXml(\Magento\Framework\View\LayoutInterface $subject, $result)
    {
        if ($this->depersonalizeChecker->checkIfDepersonalize($subject)) {
            $this->checkoutSession->clearStorage();
        }
        return $result;
    }
```

That is triggered by the following line in vendor/heidelpay/magento2/Controller/Index/Redirect
```php
// send order confirmation to the customer
$this->_orderSender->send($order);
```

The stack trace is as follows:
```
/var/www/html/vendor/magento/module-checkout/Model/Session.php:clearStorage
/var/www/html/generated/code/Magento/Checkout/Model/Session/Interceptor.php
/var/www/html/vendor/magento/module-checkout/Model/Layout/DepersonalizePlugin.php
/var/www/html/vendor/magento/framework/Interception/Interceptor.php
/var/www/html/vendor/magento/framework/Interception/Interceptor.php
/var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php
/var/www/html/vendor/magento/framework/View/Layout/Builder.php
/var/www/html/vendor/magento/framework/View/Layout/Builder.php
/var/www/html/vendor/magento/framework/View/Layout.php
/var/www/html/vendor/magento/framework/View/Layout.php
/var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php
/var/www/html/vendor/magento/module-email/Model/Template/Filter.php
/var/www/html/vendor/magento/framework/Filter/Template.php
/var/www/html/vendor/magento/module-email/Model/Template/Filter.php
/var/www/html/vendor/magento/module-email/Model/AbstractTemplate.php
/var/www/html/vendor/magento/module-email/Model/AbstractTemplate.php
/var/www/html/vendor/magento/framework/Filter/Template.php
/var/www/html/vendor/magento/framework/Filter/Template.php
/var/www/html/vendor/magento/module-email/Model/Template/Filter.php
/var/www/html/vendor/magento/module-email/Model/AbstractTemplate.php
/var/www/html/vendor/magento/module-email/Model/Template.php
/var/www/html/vendor/magento/framework/Mail/Template/TransportBuilder.php
/var/www/html/vendor/magento/framework/Mail/Template/TransportBuilder.php
/var/www/html/generated/code/Magento/Framework/Mail/Template/TransportBuilder/Interceptor.php
/var/www/html/vendor/magento/module-sales/Model/Order/Email/SenderBuilder.php
/var/www/html/vendor/magento/module-sales/Model/Order/Email/Sender.php
/var/www/html/vendor/magento/module-sales/Model/Order/Email/Sender/OrderSender.php
/var/www/html/vendor/heidelpay/magento2/Controller/Index/Redirect.php:execute
```

**Comment by zolthan** [comment]
Thank you so much @michaelscheel !!

You saved my day by posting this issue... I was searching for hours... It's not solved by your post, but I know where to search.

**Comment by sixer1182** [comment]
Hi @michaelscheel and @zolthan,
we are currently investigating this issue.
And we came accross this description https://gielberkers.com/customer-sessions-depersonalizer-caching-magento-2/.
It seems Magento is automatically clearing the session as soon as a cachable layout is rendered and the FPC is active. We will come up with a solution and post it here for you.
Sorry for the inconvenience.
Yours,
Simon

**Comment by devheidelpay** [comment]
Hi Michael,
vergiss die letzte Mail.
Ich denke ich habe jetzt den richtigen Fix gefunden.

Wir haben je nach Zahlart Info-Blöcke definiert, die sowohl auf der Success-Page, als auch in der Bestellbestätigungsmail auftauchen.
Da liegt der Hase im Pfeffer, weil der Scope der Blöcke nicht auf private gesetzt wird.

Lösung:
In der Klasse: Block/Info/AbstractBlock.php
muss folgende Zeile im Constructor ergänzt werden:
$this->_isScopePrivate = true;

Das sollte eine updatesichere Lösung bringen.
 
Bei weiteren Fragen stehe ich gerne erneut zur Verfügung.

Mit freundlichen Grüßen

Simon Gabriel
Plug-In Developer 

Phone:    +49 6221 6471 400
Fax:         +49 6221 6471 999
Mail:        development@heidelpay.com
Web:        http://www.heidelpay.com
Dev:          https://dev.heidelpay.com
Twitter:    @devHeidelpay
 
heidelpay GmbH
Vangerowstraße 18
69115 Heidelberg
 
Registergericht: Amtsgericht Mannheim, HRB 337681
Geschäftsführer: Dipl. Vw. Mirko Hüllemann, Tamara Huber, André Munk, Georg Schardt
 
Heidelpay ist ein von der Bundesanstalt für Finanzdienstleistungsaufsicht erlaubtes Zahlungsinstitut
https://portal.mvp.bafin.de/database/ZahlInstInfo/zahlinst.do?id=122914
_______________________________
Diese Mail ist ausschließlich für den genannten Empfänger bestimmt. Sie enthält persönliche oder vertrauliche Informationen. Jede unerlaubte Verbreitung des Inhalts, auch teilweise, ist untersagt. Falls Sie diese Mail versehentlich erhielten, informieren Sie bitte unverzüglich den Absender und löschen Sie diese Mail endgültig von jedem Rechner, auch Ihrem Mailserver.
This mail contains private or confidential information and is intended only for the person to which it is addressed. Any unauthorized dissemination, even partly, is prohibited. If you received this mail in error, please contact the sender and delete this mail finally from any computer, including your mail server.


-----Original Nachricht-----
Von: Michael Scheel <scheel@virtualways.de>
Gesendet: 26/06/2018 15:48:22


> Hi Simon,
> nee, leider nicht. Das Problem ist das Statement session_write_close();
> in vendor/magento/module-page-cache/Model/Layout/DepersonalizePlugin.php.
> 
> Die Methode wird aufgerufen, wenn die Mail generiert wird, ausgelöst
> durch euren Controller (Redirect.php). Da ihr die Variablen (lastQuoteId,
> usw.) zwar setzt, das aber diese nie „geschrieben“ werden, fehlen
> die Infos nach dem Redirect.
> 
> Mit der Checkout-Success-Page kann das nicht zu tun haben, die wird
> auch bisher nicht gecached, was du an dem XML-Layout unter vendor/magento/module-checkout/view/frontend/layout/checkout_onepage_success.xml
> erkennen kannst.
> 
> Magento Update hilft an der Stelle leider nicht, der Code ist in 2.2.4
> identisch und es wurden zwar einige Caching-Themen gefixt, aber nichts,
> was uns hier weiterhelfen würde.
> 
> Wir haben das momentan temporär über ein Plugin gelöst, welches
> sich in den DepersonalizeChecker reinhängt und überprüft, ob euer
> Modul im Request gesetzt ist.
> 
>  Freundliche Grüße
>  Michael Scheel
>  Geschäftsführender Gesellschafter
>    
>       0731 - 379 357 91  (tel://0731%20-%20379%20357%2091) 
>       www.virtualways.de  (http://www.virtualways.de/) 
>   virtualways GmbH // Sedanstraße 124 // D-89077 Ulm
>  Geschäftsführer: Michael Scheel, Tobias Völker
>  Amtsgericht Ulm: HRB 728823 // Sitz: Ulm

**Comment by zolthan** [comment]
Hi @sixer1182 

anything new here? Our shop still runs without tracking because no Heidelpay-Customer gets to see the success page.

Best

**Comment by sixer1182** [comment]
Hi @zolthan,
I am having trouble reproducing the error.
However I have a possible solution.
Are you open to checking it for me?
If so please send an email to our Ticket-System development@heidelpay.com

Yours,
Simon

**Comment by zolthan** [comment]
Hi @sixer1182,
I have sent you an email with my company account.
Best

**Comment by sixer1182** [comment]
Since this problem can not be reproduced there will be no further investigation at the moment.

Yours,
Simon

**Comment by zolthan** [comment]
Unfortunately, the problem reproduced in every single checkout. 

Our solution is to use the module of Customweb...

**Comment by matin73** [comment]
have same problem in 2 shops with heidelpay modul!

**Comment by matin73** [comment]
Why is this ticket closed? Bug still occures in latest version? This is realy anoying!!

**Comment by justinpfister** [comment]
So.. can anyone confirm? Is the solution to use asynchronous email??

**Comment by matin73** [comment]
@sixer1182  this is NOT Varnish cache problem!!! I already sent you emails weeks ago with same problem on server without varnish!

**Comment by sixer1182** [comment]
As of today we will disable issue tracking on GitHub.
This is due to most of the issues actually being support issues due to usage problems.
Please send your requests to support@heidelpay.com to receive a Ticket-Number.
We are sorry for any inconvenience this will cause you.
Thanks for understanding,
your HeidelpayDev team.
