### ISSUE TITLE
Feature: Display payment logos in checkout

### ISSUE THREAD

**Issue by zolthan** [heidelpay/magento2#71]
Hi Heidelpay,

our customer currently needs to have the payment logos like the Visa / Mastercard logo to be displayed in the checkout. Is there currently a schedule to implement this feature? We think it would be a good solution to raise the conversion rate.

We would implement it by ourselves, but as we all know the Magento 2 checkout, it would lead us to rewrite some of your code. 

To be able to display those payment logos, each payment type has to have a configuration setting, which payment provider should be displayed on store view level. (Like the channels could be different for each store view).

Best
Z

**Comment by zolthan** [comment]
Hi @frostblogNet ,

our customer talked to your sales department who told our customer that there is no restriction in embedding the logos on your side. I received the information you gave me now from another developer of Heidelpay.

I'm a little confused that only heidelpay has this problem. The payment modules of Paysera and Przelewy24 are using the payment logos. Also developers like customweb are using the logos https://www.sellxed.com/shop/de/chf/magento-heidelpay-zahlungs-extension.html

Maybe you could check again with your sales and get back to me again if it is really clear. 

Best
Sebastian

**Comment by frostblogNet** [comment]
Hi @zolthan 

It really depends on the contract we have with the external payment method. For example for easyCredit and Santander we are allowed to ship the icons but for visa we are not. Maybe the sales contact was not aware of this.  For other extension providers I can not say, maybe they have a different contract or maybe they even don`t care. 

For now our product owner decides no to ship the icons.

Regards

Jens

**Comment by zolthan** [comment]
Hi @frostblogNet ,

would it be possible to add a configuration field where a logo may be uploaded on StoreView level?

We will add the logos for our customer, but therefore we have to adjust your knockout templates and the javascript. So maybe it would be an idea to let your customers decide what to display.

Best
Sebastian

**Comment by sixer1182** [comment]
Hi @zolthan,
we will discuss this and come back to you.

Yours,
Simon

**Comment by sixer1182** [comment]
Hi @zolthan,
we have created a corresponding task in our backlog.
However the sales department needs to decide if and when to work on it.
This has a rather low priority since there are more urgent issues to work on as you know.
If you need a quick solution you will have to implement it yourself.

This issue will be closed for now.
Sorry for the unsatisfying answer.

Yours,
Simon
