### ISSUE TITLE
This page isn’t working After Clicking place order 

### ISSUE THREAD

**Issue by BabliDey** [heidelpay/magento2#72]
Magento version 2.1.8
Heidelpay version 17.10.12
When using sandbox credential and sandbox mode enabled the payment is working fine. But when enabling live mode and making payment getting the error 
This page isn’t working
is currently unable to handle this request.

And in log file getting
 Heidelpay - Response is NOK. Message: [Address untraceable], Reason: [INSURANCE_ERROR] (40), Code: [400.100.101], Status: [REJECTED_VALIDATION] (70) {"is_exception":false} []

**Comment by sixer1182** [comment]
Hi @BabliDey,
it seems the address you entered does not exist.
Maybe it contains a typo?
If the error persists please contact the support: support@heidelpay.com since this is an error message from the backend.

Have a nice one.
Simon

**Comment by BabliDey** [comment]
Hello @sixer1182 ,
Thanks for the reply. Can you please clarify what do you mean by address? Are you saying something about shipping address or anything else?

**Comment by sixer1182** [comment]
Hi @BabliDey,
yes I mean the shipping address.
The customers shipping address needs to exist.

Yours,
Simon

**Comment by BabliDey** [comment]
Hello @sixer1182 ,
Thanks for the reply. But the address is proper address of customer.
You can find it in google map also. 
https://www.google.com/maps/place/Norder+Ring+4,+26736+Krummh%C3%B6rn,+Germany/@53.43107,7.0853013,17z/data=!4m13!1m7!3m6!1s0x47b63b525b95e78b:0xfb937d791c2c3575!2sNorder+Ring+4,+26736+Krummh%C3%B6rn,+Germany!3b1!8m2!3d53.43107!4d7.08749!3m4!1s0x47b63b525b95e78b:0xfb937d791c2c3575!8m2!3d53.43107!4d7.08749
 

Still not redirected to checkout success page getting 
This page isn’t working
is currently unable to handle this request.

and now in debug log 
Heidelpay - Response is NOK. Message: [Increased risk], Reason: [INSURANCE_ERROR] (40), Code: [400.100.107], Status: [REJECTED_VALIDATION] (70) {"is_exception":false} []

**Comment by sixer1182** [comment]
Hi @BabliDey,
please contact our support ar support@heidelpay.com since this is an error message from the backend and we can't help you here.

Have a nice one.
Simon
