### ISSUE TITLE
Missing Event "checkout_submit_all_after" called in \Magento\Quote\Model\QuoteManagement::placeOrder

### ISSUE THREAD

**Issue by zolthan** [heidelpay/magento2#73]
Because the module doesn't use the method \Magento\Quote\Model\QuoteManagement::placeOrder, there is an event missing which triggers the correct inventory management. As a result, a module we use Amasty Multiinventory doesn't work with Heidelpay, because the inventory management is triggered by that event. The other payment methods are working fine.

It should be enough to add the event in
https://github.com/heidelpay/magento2/blob/d9b1abfb295a8e607992db1909a2cbc9064d659d/Controller/Index/Response.php#L299

``$this->_eventManager->dispatch('checkout_submit_all_after', ['order' => $order, 'quote' => $quote]);``

Although this is not a clean solution. It should be better to use the Magento 2 default procedure.

**Comment by sixer1182** [comment]
Hi @zolthan,
thanks for the issue.
We will look into it.

Yours, Simon

**Comment by sixer1182** [comment]
Hi @zolthan,
we cannot call the method \Magento\Quote\Model\QuoteManagement::placeOrder since it is not suitable for payment methods which are redirected outside the shop and then redireceted into the shop (ref. paypal). However we will add triggering the missing events in one of the next releases.

Yours,
Simon

**Comment by ksanisha** [comment]
Hi @sixer1182 Which method are we supposed to use for placing orders for payment methods which are redirected outside the shop and then redirected to the shop (ex: payments done through a mobile app which uses rest API to place orders)?

**Comment by sixer1182** [comment]
Hi @ksanisha,
I don't have time to look into this at the moment and suggest you to address this in the magento community.

If you find an answer I would be happy to here from you again.

Yours,
Simon
