### ISSUE TITLE
Order confirmation email is being sent twice

### ISSUE THREAD

**Issue by sippsolutions** [heidelpay/magento2#74]
# Prerequisites
1. Magento Commerce 2.2.5
2. PHP 7.1.20
3. Heidelpay M2 18.6.11 (Test Mode)

# Steps to reproduce
1. Create a new order as Guest
2. Select Credit Card as payment method
3. Submit order

# Expected result
1. Confirmation email is being sent to the given email address once

# Actual result
1. Confirmation email is being sent to the given email address twice

## Stack trace (Email 1, "sales_model_service_quote_submit_success" Event)

    #0 {root}vendor/magento/module-quote/Observer/SubmitObserver.php(53): Magento\Sales\Model\Order\Email\Sender\OrderSender->send(Object(Magento\Sales\Model\Order\Interceptor))
    #1 {root}vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Magento\Quote\Observer\SubmitObserver->execute(Object(Magento\Framework\Event\Observer))
    #2 {root}vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Quote\Observer\SubmitObserver), Object(Magento\Framework\Event\Observer))
    #3 {root}vendor/magento/module-staging/Model/Event/Manager.php(97): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
    #4 {root}generated/code/Magento/Staging/Model/Event/Manager/Proxy.php(95): Magento\Staging\Model\Event\Manager->dispatch('sales_model_ser...', Array)
    #5 {root}vendor/magento/module-quote/Model/QuoteManagement.php(519): Magento\Staging\Model\Event\Manager\Proxy->dispatch('sales_model_ser...', Array)
    #6 {root}vendor/magento/module-quote/Model/QuoteManagement.php(406): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Magento\Quote\Model\Quote\Interceptor), Array)
    #7 {root}vendor/heidelpay/magento2/Controller/Index/Response.php(263): Magento\Quote\Model\QuoteManagement->submit(Object(Magento\Quote\Model\Quote\Interceptor))
    #8 {root}vendor/magento/framework/App/Action/Action.php(107): Heidelpay\Gateway\Controller\Index\Response->execute()
    #9 {root}vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
    #10 {root}vendor/magento/framework/Interception/Interceptor.php(138): Heidelpay\Gateway\Controller\Index\Response\Interceptor->___callParent('dispatch', Array)
    #11 {root}vendor/magento/module-customer-segment/Model/App/Action/ContextPlugin.php(81): Heidelpay\Gateway\Controller\Index\Response\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
    #12 {root}vendor/magento/framework/Interception/Interceptor.php(135): Magento\CustomerSegment\Model\App\Action\ContextPlugin->aroundDispatch(Object(Heidelpay\Gateway\Controller\Index\Response\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
    #13 {root}vendor/magento/framework/Interception/Interceptor.php(153): Heidelpay\Gateway\Controller\Index\Response\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
    #14 {root}generated/code/Heidelpay/Gateway/Controller/Index/Response/Interceptor.php(26): Heidelpay\Gateway\Controller\Index\Response\Interceptor->___callPlugins('dispatch', Array, Array)
    #15 {root}vendor/magento/framework/App/FrontController.php(55): Heidelpay\Gateway\Controller\Index\Response\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
    #16 {root}vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
    #17 {root}vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
    #18 {root}vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
    #19 {root}vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
    #20 {root}vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
    #21 {root}vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
    #22 {root}vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
    #23 {root}generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
    #24 {root}vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
    #25 {root}vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
    #26 {root}pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
    #27 {main}

## Stack trace (Email 2)
    #0 {root}vendor/heidelpay/magento2/Controller/Index/Redirect.php(156): Magento\Sales\Model\Order\Email\Sender\OrderSender->send(Object(Magento\Sales\Model\Order\Interceptor))
    #1 {root}vendor/magento/framework/App/Action/Action.php(107): Heidelpay\Gateway\Controller\Index\Redirect->execute()
    #2 {root}vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
    #3 {root}vendor/magento/framework/Interception/Interceptor.php(138): Heidelpay\Gateway\Controller\Index\Redirect\Interceptor->___callParent('dispatch', Array)
    #4 {root}vendor/magento/module-customer-segment/Model/App/Action/ContextPlugin.php(81): Heidelpay\Gateway\Controller\Index\Redirect\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
    #5 {root}vendor/magento/framework/Interception/Interceptor.php(135): Magento\CustomerSegment\Model\App\Action\ContextPlugin->aroundDispatch(Object(Heidelpay\Gateway\Controller\Index\Redirect\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
    #6 {root}vendor/magento/framework/Interception/Interceptor.php(153): Heidelpay\Gateway\Controller\Index\Redirect\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
    #7 {root}generated/code/Heidelpay/Gateway/Controller/Index/Redirect/Interceptor.php(26): Heidelpay\Gateway\Controller\Index\Redirect\Interceptor->___callPlugins('dispatch', Array, Array)
    #8 {root}vendor/magento/framework/App/FrontController.php(55): Heidelpay\Gateway\Controller\Index\Redirect\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
    #9 {root}vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
    #10 {root}vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
    #11 {root}vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
    #12 {root}vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
    #13 {root}vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
    #14 {root}vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
    #15 {root}vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
    #16 {root}generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
    #17 {root}vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
    #18 {root}vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
    #19 {root}pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
    #20 {main}

It seems that the check for a redirect URL in `\Magento\Quote\Observer\SubmitObserver::execute` (line 51) returns nothing but should return the redirect URL for Heidelpay so the email won't be sent in this place but only in `\Heidelpay\Gateway\Controller\Index\Redirect::execute` (line 156) afterwards.

**Comment by sixer1182** [comment]
Hi @sippsolutions,
tanks for the issue.
We will look into it and keep you postet.

Yours,
Simon

**Comment by sixer1182** [comment]
Hey @sippsolutions,
this issue has been solved in Version [18.8.9](https://github.com/heidelpay/magento2/compare/18.6.11...18.8.9).

Yours,
Simon
