### ISSUE TITLE
CC redirect is stuck on hgw/index/response

### ISSUE THREAD

**Issue by muhkuh2005** [heidelpay/magento2#77]
Using **18.8.9** on **Magento 2.2.2** in **Sandboxmode** I am facing the issue of not being redirected properly after giving the nessecary CC Information.

After I chose they heidelpay creditcart payment method and click to continue the checkout I am being redirected to [base_url]/hgw/ where I am prompted to give Credit Card Information. Entering the given information from the sandbox documentation page for credit cards (Using expiry date 02/2020) I click the continue button.
The button seems to successfully omit the data to `https://test-heidelpay.hpcgw.net/ngw/paymentFrame/sendData` (Status Code 200 and response is an json object with the given informations).
After that I am forwarded to `[base_url]/hgw/index/response/?` where the process stops.
The pages only content is `[base_url]/hgw/index/redirect/`

In Magentos debug.log I can read the following statement:
`main.WARNING: Heidelpay - Response: Request is not POST. [] []`

I have also tried using **18.6.11** to see if it is an recent bug but it acts the same.
May I have some technical issues on my server side or did I maybe botched some settings?

**Comment by sixer1182** [comment]
Can you provide me a shortId for your request please?

**Comment by sixer1182** [comment]
Dear @muhkuh2005 
please contact our support which will look into what has been going on on the server side.
You can reach the support via support@heidelpay.com

Have a nice one,
Simon

**Comment by muhkuh2005** [comment]
To those that encounter similiar:
Reason was that the shop is not accessible for public use.
