### ISSUE TITLE
Possibility to define the shop identifier ourselves

### ISSUE THREAD

**Issue by codedge** [heidelpay/magento2#78]
Currently the shop identfier is set to Magentos quote id in `src/vendor/heidelpay/magento2/Controller/Adminhtml/Order/Shipment/Save.php`, line 120:

```php
// set the basket data (for amount and currency and a secret hash for fraud checking)
$heidelpayMethod->getRequest()->basketData(
    $order->getQuoteId(),
    $this->paymentHelper->format($order->getGrandTotal()),
    $order->getOrderCurrencyCode(),
    $this->encryptor->exportKeys()
);
```

Of course we could overwrite this method to set our own identifier but it also would be great to be able to define something like "Online Shop Company A - Order {{$orderId}}" in Magento Admin.

I am refering to the fields "Vwz" and "Anmerkung" in HLP and the corresponding XLS-Export.
![verwendungszweck-anmerkung](https://user-images.githubusercontent.com/4409904/45740405-8191d580-bbf5-11e8-9dc9-0f2d2f5f5682.png)

The reason behind is, that we have multiple online sales channels and its hard to find the from which channel the order came in Heidelpays HIP.

If there is currently another way to achieve this, please let me know.

**Comment by sixer1182** [comment]
Hi @codedge 
Please contact support@heidelpay.com for this.
They will tell you how to manage the payments.
If there is no solution currently available you can hand in a feature request via your sales representative at heidelpay.

Yours,
Simon
